### ISSUE TITLE
Documentation du code

### ISSUE THREAD

**Issue by charlotrudel** [Team-Arduino-Logique/Arduino-Logique#1]
Documentation manquante dans le code lui-même.

**Comment by Khaldoche** [comment]
Oui et c'est un gros travail qu'il faudra faire.

**Comment by Khaldoche** [comment]
Je propose que quelqu'un travaille sur un modèle de commentaire que l'on appliquera tous

**Comment by charlotrudel** [comment]
Je m'en charge demain!
