### ISSUE TITLE
Organisation des fichiers

### ISSUE THREAD

**Issue by charlotrudel** [Team-Arduino-Logique/Arduino-Logique#14]
Il faudrait penser à une organisation de fichiers facile à utiliser avec le code le moins long possible, séparer tout le visuel/gui de la logique, séparer les puces des plaquettes, le générateur de micro-python, la communication série/wifi, etc.

**Comment by Khaldoche** [comment]
Voici un peu l'organisation que j'avais en tête:
- Un fichier contenant les pseudos constantes et toutes les structures de données type dict ou list utiles au fonctionnement de la fonction circuit et consort.
- Un fichier contenant la fonction principal circuit 
- un fichier contenant les fonctions de dessins ou intéragissant avec le canvas:
       trou, car, planche, boitier, cabler, (entreeSortie), power...
- Un fichier avec les 3(pour le moment) fonctions transformant le circuit en script micro-python
- Un fichier contenant les fonctions et la gestion de la communication avec le mc(micro-contrôleur) série/wifi
- Un fichier la GUI (c'est le main en fait) ce fichier est vu comme le programme principal qui utilise la librairie que l'on crée
- Un fichier contenant la conception des puces et des plaquettes, en fait tous les objets utiles à un circuit, c'est normalement que des données(dict, list et tuple).

D'autres fichiers peuvent être nécessaire en fonction des nouvelles fonctionnalités qui peuvent apparaître.
