### ISSUE TITLE
Traduction du code

### ISSUE THREAD

**Issue by charlotrudel** [Team-Arduino-Logique/Arduino-Logique#2]
Il pourrait être pertinent de convertir les noms de variables et de fonctions à l'anglais pour que le logiciel soit utilisable à l'extérieur du Québec.

**Comment by Khaldoche** [comment]
J'aimerai qu'on en discute tous ensemble ce jeudi 12 sept.

**Comment by Khaldoche** [comment]
J'ai regroupé réorganisation et traduction donc cette issue est faite
