### ISSUE TITLE
Amélioration des numéros de pin_io

### ISSUE THREAD

**Issue by abbou169** [Team-Arduino-Logique/Arduino-Logique#72]
pour l'instant les numéros des pin_io sont au dessus des objets, il faudrait penser à un moyen pour les afficher dans le losange.

![image](https://github.com/user-attachments/assets/c3c42b5f-1583-4567-ac22-fa614fd65863)

**Comment by charlotrudel** [comment]
J'ajouterais: 
- Sélection du micro-contrôleur plus claire
- Affichage de l'outil I/O dans la barre plus clair 
  - ![image](https://github.com/user-attachments/assets/3e022917-35fd-4c8a-b11b-f357b164b857) on voit pas grand chose
